version: '3'
services:
    database:
        restart: always
        image: postgres:latest
        container_name: database
        ports:
            - 5432:5432
        volumes:
            - ./backend/src/main/resources/DBscripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql
        environment:
            - POSTGRES_DB=testdb
            - POSTGRES_USER=femi
            - POSTGRES_PASSWORD=1234

    backend:
        container_name: backend
        build:
            context: ./backend
        ports:
            - 5002:5002
        environment:
            SPRING_PROFILES_ACTIVE: "docker"
        depends_on:
            - database

    frontend:
        container_name: frontend
        depends_on:
            - backend
        ports:
            - 8080:80
        build:
            context: ./frontend
        links:
            - backend


