version: '3'
services:
    database:
        restart: always
        image: postgres:latest
        container_name: database
        ports:
            - 5001:5432
        volumes:
            - ./backend/src/main/resources/DBscripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql
        environment:
            - POSTGRES_DB=testdb
            - POSTGRES_USER=femi
            - POSTGRES_PASSWORD=1234

    backend:
        build:
            context: ./backend
        ports:
            - 5002:5002
        environment:
            - "SPRING_PROFILES_ACTIVE=docker"
        depends_on:
            - database

    frontend:
        build:
            context: ./frontend
        ports:
            - 5003:5003
        depends_on:
            - backend

    nginx:
        container_name: reverse_proxy80
        image: nginx:latest
        depends_on:
            - backend
            - frontend
        volumes:
            - ./.nginx/default.conf:/etc/nginx/nginx.conf
        ports:
            - 8084:80


