version: '3'
services:
    database:
        restart: always
        image: postgres:latest
        container_name: database
        ports:
            - 5001:5432
        volumes:
            - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
        environment:
            - POSTGRES_DB=testdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root

    backend:
        container_name: backend
        build:
            context: ./backend
        ports:
            - 5002:5002
        environment:
            SPRING_PROFILES_ACTIVE: "docker"
        depends_on:
            - database

    frontend:
        container_name: frontend
        depends_on:
            - backend
        ports:
            - 8080:80
        build:
            context: ./frontend
        links:
            - backend


